#!/usr/bin/env python3
"""Generate and verify a standalone Ghidra project for one LabVIEW 13.0 i386 VI.
Static only. Requires the supported runtime fingerprint and pinned decoder.
Callback slot names follow the decoder:
https://github.com/mefistotelis/pylabview/blob/5f20e23de6a386021eb955c825cc43d221f09ff1/pylabview/LVcode.py
"""
from pathlib import Path
import argparse,hashlib,json,os,shutil,subprocess,sys,xml.etree.ElementTree as ET
W=Path(__file__).resolve().parent
if __package__:
 from .toolchain import acquire_job,analysis_environment,ghidra_backend,resolve_ghidra_installation,validate_runtime
 from .make_ghidra_bundle import build
 from .vi_dispatch import scan,recognize_dispatchers
 from .vi_metadata import extract
 from .vi_facts import extract as extract_facts
else:
 from toolchain import acquire_job,analysis_environment,ghidra_backend,resolve_ghidra_installation,validate_runtime
 from make_ghidra_bundle import build
 from vi_dispatch import scan,recognize_dispatchers
 from vi_metadata import extract
 from vi_facts import extract as extract_facts
def digest(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def recognize(code,node):
 # Alternate emitter: preserve its entry trampoline at offset 40. Obtain bytes
 # directly from the original VICD, never synthesize instructions from a guess.
 from capstone import Cs,CS_ARCH_X86,CS_MODE_32
 from capstone.x86 import X86_OP_MEM,X86_OP_REG,X86_REG_EAX,X86_REG_ESI,X86_OP_IMM
 from pylabview.LVcode import getProcPtrShiftVICode
 b=code.read_bytes();start=int(node.get('InitProcOffset'),0)
 if not 40<=start<len(b):raise ValueError('Invalid initializer')
 md=Cs(CS_ARCH_X86,CS_MODE_32);md.detail=True
 found=[{'name':'InitCodePtrsProc','offset':start,'evidence':'VICD Code.InitProcOffset'}];prev=None;terminated=False
 for i in md.disasm(b[start:start+8192],start):
  ops=i.operands;pair=None
  if i.mnemonic=='mov' and len(ops)==2 and ops[0].type==X86_OP_MEM and ops[0].mem.index==0:
   if ops[0].mem.base==X86_REG_EAX and ops[1].type==X86_OP_IMM:pair=(ops[0].mem.disp,ops[1].imm)
   elif prev and ops[0].mem.base==X86_REG_ESI and ops[1].type==X86_OP_REG and ops[1].reg==X86_REG_EAX:
    po=prev.operands
    if prev.mnemonic=='mov' and len(po)==2 and po[0].type==X86_OP_REG and po[0].reg==X86_REG_EAX and po[1].type==X86_OP_IMM:pair=(ops[0].mem.disp,po[1].imm)
  if pair:
   shift,target=pair
   if shift>=0 and shift%4==0 and shift//4 not in [18,27,29] and 40<=target<len(b):
    en=getProcPtrShiftVICode(shift,4,{'major':13,'minor':0,'bugfix':0,'stage':4,'build':0})
    found.append({'name':getattr(en,'name',f'callback_slot_{shift//4}'),'offset':target,'evidence':f'MOV callback store at {i.address:#x}, slot {shift:#x}'})
  if i.mnemonic.startswith('ret'):terminated=True;break
  prev=i
 if not terminated or len(found)<2:raise ValueError('Initializer recognition failed')
 code.with_suffix('.entrypoints.json').write_text(json.dumps(found,indent=2))
def restore_entry(source,code):
 from types import SimpleNamespace
 from pylabview.LVrsrcontainer import VI
 po=SimpleNamespace(rsrc=str(source),filebase=source.stem,verbose=0,textcp='mac_roman',typedesc_list_limit=4095,array_data_limit=2**28-1,store_as_data_above=4095,print_map=None,raw_connectors=False,keep_names=False)
 with source.open('rb') as fh:
  vi=VI(po,rsrc_fh=fh,text_encoding='mac_roman');raw=vi.get_or_raise('VICD').getData().read()
 b=code.read_bytes()
 if raw[44:len(b)]!=b[44:]:raise ValueError('Raw VICD and decoder code differ')
 if raw[40]==0xe9:
  import struct
  target=45+struct.unpack_from('<i',raw,41)[0]
  scan(raw[:len(b)],require=True)
  code.write_bytes(b[:40]+raw[40:44]+b[44:])
  (code.parent/'entry-restoration.json').write_text(json.dumps({'source_sha256':digest(source),'offset':40,'original_decoded':b[40:44].hex(),'restored_from_raw_VICD':raw[40:44].hex(),'jump_target':target,'remaining_code_matches_raw':True},indent=2))
def main():
 ap=argparse.ArgumentParser(description=__doc__,formatter_class=argparse.RawDescriptionHelpFormatter)
 ap.add_argument('vi',type=Path,help='path to one extracted RSRC VI')
 ap.add_argument('--output',type=Path,required=True,help='new or empty output directory')
 ap.add_argument('--runtime',type=Path,required=True,help='supported LV13 i386 lvrt.dll supplied by the user')
 ap.add_argument('--runtime-map',type=Path,required=True,help='callback map generated by vi-runtime-map')
 ap.add_argument('--ghidra',help='Ghidra installation directory or flatpak; default: GHIDRA_HOME or analyzeHeadless on PATH')
 ap.add_argument('--embed-vi',action='store_true',help='also archive the complete input VI in the Ghidra program')
 ap.add_argument('--prepare-only',action='store_true',help='decode and validate plans without running Ghidra')
 ap.add_argument('--allow-unresolved',action='store_true',help='retain unsupported runtime relocations with explicit bookmarks; output remains incomplete')
 args=ap.parse_args()
 source=args.vi.expanduser().resolve()
 if not source.is_file():ap.error(f'VI not found: {args.vi}')
 if source.read_bytes()[:4]!=b'RSRC':ap.error('Input must be an extracted RSRC VI, not an EXE/archive')
 out=args.output.expanduser().resolve()
 if out.exists() and (not out.is_dir() or any(out.iterdir())):ap.error(f'Output is not empty: {out}; choose a new directory')
 runtime=args.runtime.expanduser().resolve();runtime_map=args.runtime_map.expanduser().resolve()
 try:
  runtime_info=validate_runtime(runtime,runtime_map)
  resource_lock,resource_limits=acquire_job()
 except (ValueError,OSError) as e:ap.error(str(e))
 out.mkdir(parents=True,exist_ok=True)
 (out/'runtime-map.json').write_text(json.dumps(runtime_info,indent=2))
 scripts=['__init__.py','__main__.py','toolchain.py','recover_callbacks.py','vi_to_ghidra.py','make_ghidra_bundle.py','vi_metadata.py','ImportLabVIEW13.java','ImportVIMetadata.java','ValidateExportLabVIEW13.java','vi_dispatch.py','RecoverVIStateDispatch.java','vi_facts.py','ImportVIFacts.java']
 snapshot=out/'reproduce';snapshot.mkdir()
 for name in scripts:shutil.copy2(W/name,snapshot/name)
 java_names={}
 for f in snapshot.glob('*.java'):
  original=f.stem;renamed=original+'_'+digest(f)[:12];text=f.read_text().replace('public class '+original+' ', 'public class '+renamed+' ');(snapshot/(renamed+'.java')).write_text(text);java_names[original+'.java']=renamed+'.java'
 env=analysis_environment()
 (out/'resource-limits.json').write_text(json.dumps(resource_limits,indent=2))
 commands=[]
 def run(stage,command,cwd=None,marker=None):
  command=[java_names.get(v,v) for v in command]
  print(f'[{source.name}] {stage}',flush=True);commands.append({'stage':stage,'argv':command,'cwd':str(cwd or out)})
  with (out/f'{stage}.log').open('w') as log:r=subprocess.run(command,cwd=cwd or out,env=env,stdout=log,stderr=subprocess.STDOUT)
  markers=[marker] if isinstance(marker,str) else (marker or [])
  if r.returncode or any(m not in (out/f'{stage}.log').read_text(errors='replace') for m in markers):raise RuntimeError(f'{stage} failed; see {out}/{stage}.log')
 try:
  decoded=out/'decoded';decoded.mkdir()
  run('decode',[sys.executable,'-m','pylabview.readRSRC','-x','-i',str(source)],cwd=decoded)
  x=decoded/(source.stem+'.xml');root=ET.parse(x,parser=ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))).getroot();ver=root.find('LVSR/Section/Version');sec=root.findall('VICD/Section')
  if ver is None or any(int(ver.get(k,'-1'),0)!=v for k,v in [('Major',13),('Minor',0),('Bugfix',0)]):raise ValueError('Supported profile is LabVIEW 13.0.0 only')
  if len(sec)!=1 or sec[0].find('General').get('CodeID')!='i386':raise ValueError('Exactly one i386 native VICD section is required')
  if int(sec[0].find('General').get('Version','0'),0)!=0x13008000:raise ValueError('Unverified VICD code version')
  node=sec[0].find('Code');code=decoded/node.get('File')
  if not code.name.isascii():
   renamed=decoded/'native-code.bin';code.rename(renamed);code=renamed;node.set('File',code.name);ET.ElementTree(root).write(x,encoding='utf-8',xml_declaration=True)
  restore_entry(source,code);recognize(code,node)
  plan=build(source.name,xml_path=x,vi_path=source,output_dir=out,runtime=runtime,runtime_map=out/'runtime-map.json',embed_vi=args.embed_vi)
  plan['dispatchers']=recognize_dispatchers(code.read_bytes(),plan)
  plan['program_name']=code.name
  plan['ghidra_installation']=resolve_ghidra_installation(args.ghidra,required=not args.prepare_only)
  plan['portable_export']=str(out/'analysis.gzf');(out/'plan.json').write_text(json.dumps(plan,indent=2))
  if plan['unresolved'] and not args.allow_unresolved:raise ValueError(f'{len(plan["unresolved"])} unresolved relocations; inspect plan.json or explicitly use --allow-unresolved with a new output directory')
  panels=list(decoded.glob('*FPH*.xml'))
  if len(panels)>1:raise ValueError('Multiple panel XML files; mapping requires review')
  metadata=extract(x,panels[0] if panels else None,out,source.name)
  facts=extract_facts(x,panels[0] if panels else None,out,plan)
  if not args.prepare_only:
   projects=out/'project';projects.mkdir()
   head,env,tool_files=ghidra_backend(plan['ghidra_installation'],out,source=source,runtime=runtime)
   (out/'ghidra-version.txt').write_text(tool_files)
   common=head+[str(projects),'VIAnalysis']
   script=['-max-cpu','1','-noanalysis','-scriptPath',str(snapshot)]
   run('import',common+['-import',str(code),'-loader','BinaryLoader','-loader-baseAddr',hex(plan['base']),'-processor','x86:LE:32:default','-cspec','windows']+script+['-postScript','ImportLabVIEW13.java',str(out/'plan.json')],marker='failed=0')
   run('dispatch',common+['-process',code.name]+script+['-postScript','RecoverVIStateDispatch.java',str(out/'plan.json')],marker='VI_DISPATCH_OK')
   run('metadata',common+['-process',code.name]+script+['-postScript','ImportVIMetadata.java',str(out/'metadata.json')],marker='VI_METADATA_OK')
   run('facts',common+['-process',code.name]+script+['-postScript','ImportVIFacts.java',str(out/'facts.json')],marker='VI_FACTS_OK')
   # Audit relocation flows in the saved program and export metadata in one reopen.
   run('export',common+['-process',code.name]+script+['-postScript','ValidateExportLabVIEW13.java',str(out/'plan.json'),'audit-only','-postScript','ImportVIFacts.java',str(out/'facts.json'),'reopen','-postScript','ImportVIMetadata.java',str(out/'metadata.json'),'export'],marker=['VI_METADATA_OK','LABVIEW_AUDIT_OK','VI_FACTS_OK'])
   run('roundtrip',head+[str(projects),'RoundTripVerification','-import',str(out/'analysis.gzf')]+script+['-postScript','ValidateExportLabVIEW13.java',str(out/'plan.json'),'audit-only','-postScript','ImportVIFacts.java',str(out/'facts.json'),'roundtrip','-postScript','ImportVIMetadata.java',str(out/'metadata.json'),'roundtrip'],marker=['VI_METADATA_OK','LABVIEW_AUDIT_OK','VI_FACTS_OK'])
   audits=[json.loads((out/f'audit-{s}.json').read_text()) for s in ['apply','export','roundtrip']]
   for key in ['code_sha256','metadata_sha256','records','fields','scalar_fields','function_signatures_sha256']:
    if len({a[key] for a in audits})!=1:raise ValueError(f'Round-trip mismatch: {key}')
   fact_audits=[json.loads((out/f'facts-audit-{mode}.json').read_text()) for mode in ['apply','reopen','roundtrip']]
   for key in fact_audits[0]:
    if key!='mode' and len({a[key] for a in fact_audits})!=1:raise ValueError(f'Facts round-trip mismatch: {key}')
  report={'ghidra_installation':plan['ghidra_installation'],'source':str(source),'source_sha256':digest(source),'original_vi_embedded':plan['original_vi_embedded'],'mode':'prepare-only' if args.prepare_only else 'verified-project','project':str(out/'project/VIAnalysis.gpr') if not args.prepare_only else None,'gzf':str(out/'analysis.gzf') if not args.prepare_only else None,'dispatchers':len(plan['dispatchers']),'dispatcher_states':sum(len(d['targets']) for d in plan['dispatchers']),'callbacks':len(plan['entries']),'relocations':len(plan['changes']),'unresolved_relocations':len(plan['unresolved']),'metadata_records':len(metadata['records']),'ds_fields':len(metadata['fields']),'scalar_fields':sum(f['type'] is not None for f in metadata['fields']),'connected_controls':sum(d['control'] is not None for d in metadata['dcos']),'panel_xml_present':bool(panels),'limitations':metadata['limitations']}
  report['facts_layout_status']=facts['layout']['status']
  report['facts_layout_reasons']=facts['layout']['reasons']
  report['limitations']+=facts['limitations']
  if not args.prepare_only:
   report['facts_audit']=fact_audits[-1]
   report['dispatcher_recovery']=json.loads((out/'dispatcher-recovery.json').read_text())
   report['decompiled_callback_files']=len(list((out/'decompiled').glob('*.c')))
   if any(not r['decompiled'] for r in report['dispatcher_recovery']):
    report['limitations']=report['limitations']+['Dispatcher flow/table/body verified, but whole RunProc decompilation failed or timed out. Use vi-state-views for bounded pseudocode fragments; unknown runtime prototypes can hide real arguments.']
  (out/'result.json').write_text(json.dumps(report,indent=2))
  print(json.dumps(report,indent=2),flush=True)
 except Exception as e:
  (out/'FAILED.json').write_text(json.dumps({'error':str(e)},indent=2));raise
 finally:
  resource_lock.close()
  (out/'commands.json').write_text(json.dumps(commands,indent=2))
  (out/'manifest.json').write_text(json.dumps({'inputs':{str(source):digest(source),str(runtime):digest(runtime),str(runtime_map):digest(runtime_map)},'scripts':{str(f):digest(f) for f in snapshot.iterdir() if f.is_file()},'outputs':{str(p.relative_to(out)):digest(p) for p in out.iterdir() if p.is_file() and p.name!='manifest.json'}},indent=2))
if __name__=='__main__':main()
